config/routes.rb
CanRecover::Application.routes.draw do
  resources :pins

  devise_for :users
  
  root "pages#home"
  get "medical_overview" => "pages#medical_overview"
  get "story" => "pages#story"
  get "support" => "pages#support"
  get "contact" => "pages#contact"
  get "blog" => "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image

	validates :image, presence: true
  validates :description, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def medical_overview
  end

  def story
  end

  def support
  end

  def contact
  end

  def blog
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_donate.html.erb
<div class="donate-background">
	<div class="donate-container clear">
		<h1>Help Our Cause.</h1>
		<br><br>
		<p>All donations go toward helping CAN Recover achieve its mission to support the student-athlete suffering post concussion syndrome, educate the community surrounding them, and expedite clinical research efforts.<br><br>
		We greatly appreciate your support!<p> 
			<br><br>
		<div id="home-donate-pic"><%= image_tag "sprout.png" %></div>
		<div id="paypal"><%= image_tag "paypal.png", alt: "Secure Payments by PayPal", style: "margin-left: -25px;" %><%= button_to "Donate", support_path, class: "btn btn-lg btn-success", method: "get" %></div>
	</div><!-- Donate Container Ends -->
	<br><br><br><br>
</div><!-- Donate Background Ends -->

app/views/layouts/_footer.html.erb
<div class="footer-background clear">
	<div class="footer-container clear">
		<br><br>
		<div class="center"><%= image_tag "canrecoverlogo.png", alt: "CanRecover Logo" %></div>
		<br>
		<p><strong>Find Support With Us</strong>
			<br><br>
			<%= link_to "Medical Overview", medical_overview_path %><br>
			<%= link_to "Contact Us", contact_path %><br>
		</p>

		<p><strong>About CAN Recover</strong>
			<br><br>
			<%= link_to "Our Stories", story_path %><br>
			<%= link_to "Blog", blog_path %><br>
			<%= link_to "Twitter", "https://twitter.com/CANrecover", target: "_blank" %><br>
			<%= link_to "Facebook", "http://www.facebook.com/CANrecover", target: "_blank" %>
		</p>

		<p><strong>How to Help</strong>
			<br><br>
			<%= link_to "Donate", support_path %><br>
			<%= link_to "Volunteer", contact_path %><br>
			<%= link_to "Sponsor an Event", contact_path %>
		</p>
		<div class="footer-address clear"><br>PO Box 132, Rye, NH, 03870 <br>© CAN Recover Foundation, Inc. 2014. All Rights Reserved.<br>
			<%= link_to "Admin", new_user_session_path %>
			
			<% if user_signed_in? %>

			|  <%= link_to 'New Post', new_pin_path %> | <%= link_to "Settings", edit_user_registration_path %> | 
			<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
			<% end %></div><br><br>
	</div><!-- Div Container Ends -->
</div>

app/views/layouts/_header.html.erb
<div class="navbar-background-color">
  <div class="container">
    <div class="float-left"><%= link_to image_tag("canrecoverlogo.png", alt: "CanRecover Logo"), root_path %></div>
    <div class="float-right">
      <div class="navlinks">
        <%= link_to "Home", root_path %>
        <%= link_to "Our Stories", story_path %>
        <%= link_to "Medical Overview", medical_overview_path %>
        <%= link_to "Get Involved", support_path %>
        <%= link_to "Blog", blog_path %>
        <%= link_to "Contact", contact_path %>
      </div><!-- Navlinks Ends -->
    </div>

    <!-- <div class="social-media-bar">
      <%= link_to (image_tag "f.png"), "http://www.facebook.com/CANrecover", target: "_blank" %>
      <%= link_to (image_tag "t.png"), "https://twitter.com/CANrecover", target: "_blank" %>
    </div>--><!-- Social Media Bar Ends --> 
  </div><!-- Navbar Container Ends -->
</div>

app/views/layouts/_pvc.html.erb
<div id="pvc"><span class="patient-view-text">Viewer Options</span></div>
<div id="pvc-inner">
	<p>www.CANrecover.org is specifically designed for concussion patients who often have difficulty reading screens. Patient View 1 and 2 are the two most comfortable designs we identified for concussion patients. The Traditional View is targeted towards nonconcussion patients.</p>
	<ul>
		<li id="pv1">Patient View 1 [Default]</li>
		<li id="pv2">Patient View 2</li>
		<li id="pv3">Traditional View</li>

		<li id="fs-plus">Font-size +</li>
		<li id="fs-minus">Font-size -</li>
	</ul>
</div>

<!-- jQuery Effect for Slider Tab -->
<script>
	$(document).ready(function(){
		$('#pvc').click(function(){
			$('#pvc').toggleClass("add-bottom");
			$('#pvc-inner').toggleClass("add-bottom-2");
		});

		$('#pv1').click(function() {
			$('.navbar-background-color, .home-background, .home, .story-background, .overview-background, .support-1-background, .supportbox, .blog-background, .contact-background').css({"color" : "#FFF", 'background-color' : "#4B4B4B"});
			$('.navlinks > a, .home p').css("color", "#FFF");
			$('.donate-background, .support-background').css({"background-color" : "#1C1C1C", "color" : "#FFF"});
			$('.footer-background').css("background-color", "#151515");
			$('.footer-background a, .footer-background p, .footer-address').css("color", "#FFF");
			$('.navbar-background-color').css("box-shadow", "1px 1px 1px #2E2E2E")
		});

		$('#pv2').click(function() {
			$('.home-background, .home, .navbar-background-color, .story-background, .overview-background, .support-1-background, .supportbox, .blog-background, .contact-background').css({"background-color": "#D8D8D8", "color": "black"});
			$(".navlinks a, .home p").css("color", "black");
			$('.donate-background, .support-background').css({"background-color" : "#C4C4C4", "color" : "black"});
			$('.footer-background').css("background-color", "#ABABAB");
			$('.footer-background a, .footer-background p, .footer-address').css("color", "black");
			$('.navbar-background-color').css("box-shadow", "1px 1px 1px #B7B7B7");
		});

		$('#pv3').click(function() {
			$('.home-background, .home, .navbar-background-color, .story-background, .overview-background, .support-1-background, .supportbox, .blog-background, .contact-background').css({"background-color": "#FFF", "color": "black"});
			$(".navlinks a, .home p").css("color", "black");
			$('.donate-background, .support-background').css({"background-color" : "#F5F8FA", "color" : "black"});
			$('.footer-background').css("background-color", "#3E3E3E");
			$('.footer-background a, .footer-background p, .footer-address').css("color", "#FFF");
			$('.navbar-background-color').css("box-shadow", "1px 1px 1px #DDDDDD");
		});

		$('#fs-plus').click(function() {
			$('.home h1, .home h3, .home p, .donate-container h1, .donate-container p, .story-container p, .story-container h1, .founder-portrait-name h1, .founder-storybox p, .overview-container h1, .overview-container p, .support-1-background .support-container h1, .support-background .support-container h1, .supportbox h3, .supportbox p, #blogtitle, #blogauthor, #blogbody, .contact-wrap p').css("font-size", "+=1");
			$('.supportbox').css("height", "+=15");
		});

		$('#fs-minus').click(function() {
			$('.home h1, .home h3, .home p, .donate-container h1, .donate-container p, .story-container p, .story-container h1, .founder-portrait-name h1, .founder-storybox p, .overview-container h1, .overview-container p, .support-1-background .support-container h1, .support-background .support-container h1, .supportbox h3, .supportbox p, #blogtitle, #blogauthor, #blogbody, .contact-wrap p').css("font-size", "-=1");
			$('.supportbox').css("height", "-=15");
		});
	}); 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CAN Recover Foundation</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Concussion Awareness Network for Student Athletes"/>
  <meta name="keywords" content="concussion, college, students, athlete, student athlete"/>
  <%= favicon_link_tag 'favico.png' %>
  <%= csrf_meta_tags %>
  <script> 
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53637371-1', 'auto');
  ga('send', 'pageview');
	</script>
</head>
<body>
<%= render "layouts/header" %>
<%= render "layouts/pvc" %> <!-- Patient View Controller -->
<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>

app/views/pages/contact.html.erb
<div class="contact-image-container center">
	<%= image_tag("contactus.jpg", alt: "Babson Rugby") %>
</div><!-- Contact Image Ends -->

<div class="contact-overlay-text">
	<div class="overlay-text-container">
		<h1>Contact Us Today.</h1>
	</div>
</div><!-- Contact Overlay Text Ends -->

<div class="contact-background clear">
	<div class="contact-wrap">
		<div class="contact-container-1">
			  	<br>
			  <form method="post" action="mailto:canrecover@gmail.com?subject=I want to be involved with CAN Recover" enctype="text/plain" id="form1">
			  	<div class="input-group">
			  		<span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
					  <input type="text" class="form-control" placeholder="Your Name *" name="Name" id="fname">
					</div>
						<br>
					<div class="input-group">
					  <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
					  <input type="text" class="form-control" placeholder="Your Email *" name="Email" id="femail">
					</div>
						<br>
					<div class="input-group">
					  <span class="input-group-addon"><span class="glyphicon glyphicon-pencil"></span></span>
					  <textarea rows="10" class="form-control" placeholder="Your Message *" name="Message" id="fmessage"></textarea>
					</div>
					<br>
					<p>* Required</p>
					<div id="required-field">
						<div class="required" id="the-name">Name Required!</div>
						<div class="required" id="the-email">Email Required!</div>
						<div class="required" id="the-message">Message Required!</div>
					</div>

					<p>Thank you for your mail.  We will work to get back to you within 24 hours.</p>
					<br>
					<button type="button" onclick="processForm()" class="btn btn-lg btn-info pull-left">Send</button>
				</form><!-- Form Ends -->
					<br><br><br><br><br>
		</div><!-- Contact Container 1 Ends -->
		<div class="vertical-hr3"></div>

		<div class="contact-container-2">
			<p>Inquiries will be delivered to: <br><br>[ Aaron Rocha, Co-Founder & CEO CANrecover@gmail.com ]</p>

			<br>

			<div class="fb-like" data-href="https://www.facebook.com/CANrecover" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
			<br><br>
			<a href="https://twitter.com/CANrecover" class="twitter-follow-button" data-show-count="true" data-lang="en">Follow @CANrecover</a>

		</div><!-- Contact Container 2 Ends -->
	</div><!-- Contact Wrap Ends -->
</div><!-- Contact Background Ends -->

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/pages/home.html.erb
<div class="homepage-image-container">
	<%= image_tag("babson-home.jpg", alt: "Babson Student Athlete") %>
</div><!-- Homepage Image Ends -->

<div id="parallelogram"></div>

<div class="homepage-overlay-text">
	<div class="overlay-text-container">
		<h3>Support.</h3><h2>Educate.</h2><h1>Advance.</h1><br>
		<%= button_to "Support Our Mission", support_path, class: "btn btn-lg btn-warning", method: "get" %>
	</div>
</div><!-- Homepage Overlay Text Ends -->
<div class="home-background">
	<div class="home-description clear">
		<div class="home">
			<h1>CAN Recover Foundation</h1><br><br>
			<p>CAN Recover Foundation’s mission is to provide support for student-athlete’s suffering post-concussion syndrome and educate those in the community surrounding them. Studies have shown that a student-athlete undergoing a prolonged concussions recovery would find another student-athlete who has experienced it first hand to be most trustworthy, effective, and empathetic. CAN Recover is the only organization to provide this support.</p>
			<br><br>
			<%= button_to "Read Our Story", story_path, class: "btn btn-lg btn-primary", method: "get" %>
		</div>
		<div class="vertical-hr"></div>
		<div class="home">
			<h1>What We Do.</h1>
			<p style="padding-left: 5px;">We protect the health of student athletes.</p>
			<br><br>

			<div class="wwd-1">
				<%= image_tag "soccergirl.jpg", class: "img-circle" %>
			</div>
			<div class="wwd-2">
				<h3>Support Patients</h3>
					<p>The first and only peer-to-peer support network provided for student-athletes suffering post-concussion syndrome.</p>
			</div>
			<br>
			<div class="wwd-1">
				<%= image_tag "stretching.jpg", class: "img-circle" %>
			</div>
			<div class="wwd-2">
				<h3>Educate the Community</h3>
					<p>Through fundraisers and awareness events, we help educate the community surrounding student-athletes to create a healthy environment.</p>
			</div>
			<br>
			<div class="wwd-1">
				<%= image_tag "aaronclinicalstudy.jpg", alt: "Aaron Rocha at Clinical Study", class: "img-circle" %>
			</div>
			<div class="wwd-2">
				<h3>Expedite Clinical Research<h3>
					<p>We collaborate with some of the top research teams in the world on how to expedite efforts on traumatic brain injury research!</p>
			</div>
		</div><!-- Home Ends -->
	</div><!-- Home Description Ends -->
</div><!-- Home Background Ends -->
<%= render "layouts/donate" %>

app/views/pages/medical_overview.html.erb
<div class="story-image-container center">
	<%= image_tag("collision.jpg", alt: "Concussions") %>
</div><!-- Story Image Ends -->

<div class="story-overlay-text">
	<div class="overlay-text-container">
		<h1>"The first step toward change is awareness."</h1><br>
		<h5>- Nathaniel Branden</h5>
	</div>
</div><!-- Story Overlay Text Ends -->

<div class="overview-background">
	<div class="overview-container">
		<h1 class="center">Truths about Concussions</h1>
		<p style="text-align:center">Source: <a href="http://www.childrenshospital.org/health-topics/conditions/concussions" target="_blank">Boston Children's Hospital</a></p>
		<br><br>
		<p class="overview-text bold">"What is a concussion anyway?"</p><br>
		<p class="overview-text">
			Concussions are traumatic brain injuries that result from the brain going into a spinning motion. This is most often because of a direct blow to the head, but can also be caused by a blow to the body that snaps the head forward or backward.
		</p>
		<br>
		<p class="overview-text">Sometimes, a concussion causes an immediate loss of consciousness, but a child can also appear fine at first and then have symptoms develop later. Symptoms of a concussion usually include:</p><br>
		<ul class="overview-text">
			<li>headaches</li>
			<li>difficulty falling or staying asleep (insomnia) or excessive sleepiness</li>
			<li>nausea</li>
			<li>dizziness</li>
			<li>confusion</li>
			<li>difficulty concentrating</li>
			<li>difficulty remembering things</li>
			<li>problems with balance and coordination</li>
		</ul><br>
		<p class="overview-text">
			<%= image_tag "alone.jpg", alt: "Aaron Rocha Lacrosse", class: "overview-text-photos" %>
			
			These symptoms can last anywhere from a few minutes to a few weeks after the injury. All concussions cause some disruption to the brain, and call for an exam by your child’s regular doctor as well as careful monitoring.
		</p>
		<br>
		<p class="overview-text">The good news is that most concussions don’t cause any lasting effects, and most children make a complete recovery with physical and mental rest. Even when concussions lead to complications, advances in concussion diagnostics and treatment make the majority of cases very treatable.</p>
		</p>
		<br>
		<p class="overview-text bold">“Why is there such a focus on concussions in student-athletes?"</p><br>

		<p class="overview-text">While children frequently sustain concussions for other reasons – falls or car accidents, for example – student-athletes are at particular risk. According to the U.S. Department of Health and Human Services’ Centers for Disease Control and Prevention, as many as 3.8 million concussions happen each year in the U.S. during sports or recreational activities. This is especially troubling because:</p><br>
		<ul class="overview-text">
			<li>an athlete who has had a concussion is at increased risk of suffering another</li>
			<li>athletes can develop second impact syndrome if they sustain another concussion before a prior concussion has fully healed. This is a rare but severe syndrome that can cause swelling in the brain, brain damage, coma and even death.</li>
		</ul><br>

		<p class="overview-text">For more information, please visit the <a href="http://www.childrenshospital.org/health-topics/conditions/concussions" target="_blank">Boston Children’s Hospital</a> website.</p><br>

		<p class="overview-text italic">DISCLAIMER:  NO INFORMATION ON THIS SITE SHOULD BE PERCEIVED AS MEDICAL ADVICE.  PLEASE CONTACT YOUR DOCTOR WITH ANY MEDICAL RELATED QUESTIONS YOU MAY HAVE.</p>

		<br><br><br><br>
	</div><!-- Overview Container Ends -->
</div><!-- Overview Background Ends -->

app/views/pages/support.html.erb
<div class="support-image-container center">
	<%= image_tag("support.jpg", alt: "Babson Rugby") %>
</div><!-- Support Image Ends -->

<div class="support-overlay-text">
	<div class="overlay-text-container">
		<h1>"None of us is as smart as all of us."</h1>
		<h5 style="color: #BD9712;">- Ken Blanchard</h5>
		<%= button_to "Donate", "#donatehere", class: "btn btn-lg btn-success", method: "get" %>
	</div>
</div><!-- Support Overlay Text Ends -->

<div class="support-1-background">
	<div class="support-container clear">
			<h1 class="center" id="donatehere">Please Donate</h1><br><br>
				<div class="home" style="margin-left: 3%">
					<p style="text-align: justify">Your support is very important to us. Without your donations, time volunteered, word of mouth, and all that our supporters contribute, CAN Recover would not be able to deliver its mission to thousands of people who need it. We greatly appreciate your support for our cause.</p><br>
					<p>There are two ways to donate money directly to CAN Recover Foundation, Inc:</p><br>
					<p>1.	Mail a check written out to “CAN Recover Foundation, Inc.” to PO Box 132, Rye, NH 03870</p>
					<p>2.	Donate through PayPal with your credit card.</p><br><br>
					<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
						<input type="hidden" name="cmd" value="_s-xclick">
						<input type="hidden" name="hosted_button_id" value="KWWYGZGFEFL46">
						<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
						<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
					</form>
				</div>
				<div class="home right">
					<%= image_tag "aaron.jpg", alt: "Aaron Rocha, Co-Founder of CAN Recover", class: "img-thumbnail" %>
				</div>
		</div>
	</div><!-- Support Container Ends -->
</div><!-- Support-1-Background Ends -->

<div class="support-background clear">
	<div class="support-container center">
		<h1>Want to Help?</h1>

		<div class="supportbox">
			<h3>Join Our Network</h3>
			<br>
			<%= image_tag "join-network.png" %>
			<br><br><br>
			<p style="text-align: justify">Stay up to date by simply emailing newsletter@canrecover.org. We'll give you our latest news, upcoming events, and breakthroughs in research.</p>
		</div>

		<div class="supportbox">
			<h3>Volunteer</h3>
			<br>
			<%= image_tag "volunteer.png" %>
			<br><br><br>
			<p style="text-align: justify">If you or your organization would like to volunteer time or services to CAN Recover, please contact us below and we will get in touch with you on how you can start helping support our cause!</p>
		</div>

		<div class="supportbox">
			<h3>Organize an Event</h3>
			<br>
			<%= image_tag "organize.png" %>
			<br><br><br>
			<p style="text-align: justify">If you or your organization would like to put on an awareness of fundraising event on behalf of CAN Recover, please contact us below and we can start planning together!</p>
		</div>
		<%= button_to "Contact Us Now", contact_path, class: "btn btn-lg btn-success", method: "get" %>

	</div><!-- Support Container Ends -->
</div><!-- Support Background Ends -->

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Post %>
    <%= f.text_area :description, class: "form-control", rows: 20 %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Post", class: "btn btn-primary", rows: "8" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="blog-background">
	<div class="devise-container">
		<h1>Edit Post</h1>

		<%= render 'form' %>

		<%= link_to raw('<span class="glyphicon glyphicon-chevron-left"></span> Back'), pins_path %> |
		<%= link_to raw('<span class="glyphicon glyphicon-trash"></span> Delete'), @pin, method: :delete, data: { confirm: 'This is permanent. Are you sure?' } %>
	</div>
</div>

app/views/pins/index.html.erb
<div class="blog-background">
  <div class="devise-container">
    <% @pins.each do |pin| %>
      <div class="center" style="font-family: arial;">
        <br><br><br>
        <h1 id="blogtitle"><%= pin.title %></h1>
      </div><!-- Header Title Ends -->
      <br>
      <div class="center author-date" id="blogauthor" style="font-family: arial;">
        <p>written by <%= pin.user.name %></p>
        <p><%= pin.created_at.strftime("%B %d, %Y") %></p>
      </div><!-- Author & Date Ends -->
      <br>
      <div class="center blogimage">
        <%= image_tag pin.image.url %>
      </div><!-- Post Image Ends -->
      <br>
      <div class="blog-body" id="blogbody" style="font-family: arial;">

        <%= truncate_html((pin.description), length: 750, omission: "...") %>
        <%= link_to "Continue ⇀", pin, style: "color: #BC992F" %>
      </div><!-- Blog Body Ends -->
      <br>
      <div class="center">
        <%= button_to "Read", pin, class: "btn btn-lg btn-success", method: "get" %>
      </div>
      <br>
      <div class="center">
        <% if pin.user == current_user %>
          <%= link_to raw('<span class="glyphicon glyphicon-edit"></span> Edit'), edit_pin_path(pin) %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span> Delete'), pin, method: :delete, data: { confirm: 'This is permanent. Are you sure?' } %>
        <% end %>
      </div><!-- Footer links -->
      <hr>
    <% end %>
    <br>
    <div class="center paginate">
       <%= will_paginate @posts %>
    </div>
  </div>
</div>

app/views/pins/new.html.erb
<div class="blog-background">
	<div class="devise-container">
	<h1>Write a New Blog</h1>
	<br>

	<%= render 'form' %>
	<%= link_to raw('<span class="glyphicon glyphicon-chevron-left"></span> Back'), pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<div class="blog-background">
	<div class="devise-container">
		<head>
			<div class="center">
				<h1><%= @pin.title %></h1>
			</div><!-- Header Title Ends -->
		</head>
		<br>
		<div class="center author-date">
			<p>written by <%= @pin.user.name %></p>
			<p><%= @pin.created_at.strftime("%B %d, %Y") %></p>
		</div><!-- Author & Date ends -->
		<br>
		<div class="blogimage center">
			<%= image_tag @pin.image.url %>
		</div><!-- Blog Post Images -->
		<br>
		<body>
			<div class="blog-body">
			 <%= truncate_html((@pin.description), length: 999999999, omission: "...") %>
			</div><!-- Blog Body Ends -->
			<br>
			<div class="center">
				<p>written by <%= @pin.user.name %></p>
				<p><%= @pin.created_at.strftime("%B %d, %Y") %></p>
			</div><!-- Footer Ends -->
		</body>
		<div class="center">
			<% if @pin.user == current_user %>
				<%= link_to raw('<span class="glyphicon glyphicon-edit"></span> Edit'), edit_pin_path(@pin) %>
		    <%= link_to raw('<span class="glyphicon glyphicon-trash"></span> Delete'), @pin, method: :delete, data: { confirm: 'This is permanent. Are you sure?' } %>
			<% end %>

			<%= link_to raw('<span class="glyphicon glyphicon-chevron-left"></span> Back'), pins_path %>
		</div><!-- Footer links -->
	</div>
</div>